- name: configure catalogue component
  hosts: catalogue
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: "dnf module disable nodejs -y"
    
  - name: enable nodejs:20
    ansible.builtin.command: "dnf module enable nodejs:20 -y"

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
   
  - name: create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
      comment: "roboshop system user"
  
  - name: create /app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
  
  - name: extract catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    community.general.npm:
      path: /app
  
  - name: copy the catalgoue service to systemd 
    ansible.builtin.copy:
      src: service/catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: systemctl daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
    
  - name: enable and restart catalogue service
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: repos/mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.dnf:
      name: mongodb-mongosh
      state: present

  - name: check whether products loaded or not
    ansible.builtin.command: mongosh --host mongodb.robosyed.space --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: pirnt catalogue output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: load proudcts  
    ansible.builtin.shell: "mongosh --host mongodb.robodevops.store </app/db/master-data.js"
    when: catalogue_output.stdout | int < 0
  