- name: configure payment component
  hosts: payment
  become: yes
  tasks:
    - name: install python
      ansible.builtin.package:
        name:
         - python3
         - gcc
         - python3-devel
        state: present

    - name: create a user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: true
        comment: "roboshop system user"
    - name: create an app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download the code for payment
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
        dest: /tmp/payment.zip
    - name: unarchive the code
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
    - name: install the dependencies
      ansible.builtin.shell: pip3 install -r requirements.txt
      args:
        chdir: /app
    - name: create the custom service
      ansible.builtin.copy:
        src: services/payment.service
        dest: /etc/systemd/system/payment.service
    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: enable and start the service
      ansible.builtin.service:
        name: payment
        enabled: yes
        state: started