- name: install and configure rabbitmq
  hosts: database
  become: yes
  tasks:
    - name: copy rabbitmq.repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo
    - name: install rabbitmq
      ansible.builtin.package:
        name: rabbitmq-server
        state: present
    - name: enable and start rabbitmq
      ansible.builtin.service:
        name: rabbitmq-server
        enabled: yes 
        state: started
    - name: create user
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
    - name: set permissions
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"