- name: configuring shipping
  hosts: shipping
  become: yes
  tasks:
  - name: install maven
    ansible.builtin.package:
      name: maven
      state: present 
  - name: create a roboshop user. 
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app
      system: true
      comment: "roboshop system user"
  - name: create a directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: Download the code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
      dest: /tmp/shipping.zip
  - name: unzip the code
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes
  - name: install the dependencies 
    ansible.builtin.shell: mvn clean package
    args:
      chdir: /app 
  - name: move the jar file 
    ansible.builtin.copy:
      src: /app/target/shipping-1.0.jar
      dest: shipping.jar
      remote_src: yes
  - name: create the custom service 
    ansible.builtin.copy:
      src: services/shipping.service
      dest: /etc/systemd/system/shipping.service
  - name: daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: install mysql client
    ansible.builtin.package:
      name: mysql
      state: present

  - name: check cities schema exists or not
    ansible.builtin.command:  mysql -h mysql.daws76s.online -uroot -pRoboShop@1  -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: schema

  - name: print output
    ansible.builtin.debug:
      msg: "schema output: {{schema}}"

  - name: load cities data
    ansible.builtin.shell: "mysql -h mysql.daws76s.online -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
    when: schema.stdout != "1"

  - name: start and enable shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabled: yes
